language: ruby
services:
  - docker

cache:
  directories:
    - $HOME/docker

matrix:
  include:
   - arch: amd64
     env: PLATFORM="x86_64"

script:
  - PLATFORM=$PLATFORM TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh