FROM arm64v8/ubuntu:noble

RUN apt update
RUN apt install -y gnupg
# Script to choose Python version
# Installer script for Pythons
COPY build_install_pythons.sh /

# Install Pythons and matching pips
RUN bash build_install_pythons.sh && rm build_install_pythons.sh

# Install manylinux2014 libraries. See:
# https://peps.python.org/pep-0599/#the-manylinux2014-policy
# https://github.com/multi-build/multibuild/issues/106
RUN apt-get update && \
        apt-get install -y libc6 libgcc1 libgl1 libglib2.0-0 libice6 libsm6 libstdc++6 libx11-6 libxext6 libxrender1 libssl-dev libffi-dev

# Get virtualenv
RUN pip3.10 install --user virtualenv

# Run Python selection on way into image
COPY choose_python.sh /usr/bin/
ENTRYPOINT ["/usr/bin/choose_python.sh"]
